### PR TITLE
Ship a custom set of icons

### LINKED ISSUE #40: In some environments icons are not properly loaded
As mentioned in https://github.com/robotology/robotology-superbuild/pull/1069#issuecomment-1088714626, on some environments such as conda-forge on Windows or conda-forge on non-Debian Linux distributions, the icons of the gui are not correctly loaded. 

The problem have been known for some time I think, I opened this issue just to have a reference.

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This fixes #40 

I got the icons from https://ionic.io/ionicons/usage

I don't think there are license problem

cc @traversaro

### CODE REVIEW

**Comment by traversaro** [comment]
> I don't think there are license problem
> 
> cc @traversaro

To comply with https://github.com/ionic-team/ionicons/blob/3ec9271e8369cd7f17005b4f32189b2e16c70049/LICENSE, you just need to copy that license somewhere. Furthemore, can you report the exact commit from which you took the icons? Thanks!

**Review by traversaro — APPROVED** [review]
Minor comments.

**Comment by traversaro** [comment]
Anyhow, we can just convert the comments in issues and merge as it is.

**Comment by GiulioRomualdi** [comment]
Icons taken from: https://github.com/ionic-team/ionicons/releases/tag/v6.0.1

**Pull request merged**
