### PR TITLE
Yarp port client

### PR DESCRIPTION
**Pull request by nicktrem**
Added a YARP port to the robot-log-visualizer to accept real-time data which can be visualized during testing.

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
Hi @nicktrem thank you for your contribution 😄 Can you try to resolve the conflict?

**Comment by nicktrem** [comment]
@GiulioRomualdi The merge conflict was simple and has been resolved

**Comment by nicktrem** [comment]
Made a few more commits using the GitHub online editer to remove whitespace as per the merge request requirement

**Comment by nicktrem** [comment]
This pull request is not to be merged yet! It seems the merge caused some issues with the RT visualizer, I am investigating now

**Pull request closed without merging**
